### ISSUE TITLE
WEPPCLIFF installation failed

### ISSUE THREAD

**Issue by frengers** [ryanpmcg/WEPPCLIFF#1]
I tried to run the Autotest.sh and it failed because I didn't have the "backports" package installed in R.  However, after I installed the package, I got the same error message and Autotest.sh once again failed.

**Comment by kbarnhart** [comment]
@frengers sorry I didn't notice that you had opened this here.  I'm linking it to the JOSS review.
openjournals/joss-reviews/issues/2029

**Comment by ryanpmcg** [comment]
@frengers I believe this failed for you because the autotest script assumes installation has already been completed. This is covered in the documentation. However, as recommended [here](https://github.com/ryanpmcg/WEPPCLIFF/issues/2), the installation will be made a separate task from the tutorial and test scripts.

**Comment by ryanpmcg** [comment]
@frengers will you close this issue if you find that installation proceeds as expected (using either the old or new convention).

**Comment by ryanpmcg** [comment]
@frengers opted out of completing the review, so I am closing this issue since there is no problem with installation.
