### ISSUE TITLE
No results in the OUTPUT folder when runing AutoTest.bat

### ISSUE THREAD

**Issue by marianadobre** [ryanpmcg/WEPPCLIFF#14]
I tried to run AutoTest.bat and got the following error:

![image](https://user-images.githubusercontent.com/37674030/80557062-83537b80-898a-11ea-806d-77e30359577a.png)

I then reinstalled WEPPCLIFF with the command below, which was again successful. 

"C:\Program Files\R\R-3.6.3\bin\Rscript.exe" --vanilla C:\WEPPCLIFF\WEPPCLIFF.R --args -fr t

But when running AutoTest.bat, I am getting the same error. 

Not sure if this is related to my previous issues with the installation or if this is something new?

**Comment by ryanpmcg** [comment]
I have already updated the AutoTest Script. You can try again when ready. I think the problem was that I was using 'cd ..' rather than 'cd..' (but I have changed it to search the C:/ drive for the WEPPCLIFF folder and use absolute paths, which should be more reliable anyway now).

Be aware that if you are not in the ET timezone, CLI Test 1 may not pass until I change the default behavior from using the system timezone to a set timezone (Issue #7).

**Comment by ryanpmcg** [comment]
@marianadobre I forgot to add your moniker to the comment above.

**Comment by marianadobre** [comment]
I am getting the exact same error as above. The AutoTest runs but doesn't generate anything in the outputs. The error message says the installation failed.

**Comment by ryanpmcg** [comment]
OK @marianadobre, I have hard-coded the C:\WEPPCLIFF directory into the new Install.bat, AutoTutorial.bat, and AutoTest.bat. They should all work for you now, though they are not working as I intended for them to. I don't know how to get the batch script to behave like the command line. Let me know if you have trouble running any of them. Keep in mind that the AutoTest design is undergoing changes and may not be consistent yet.

**Comment by marianadobre** [comment]
I was getting the same error. So I deleted everything and started again from cloning WEPPCLIFF and reinstalling it. 
The installation was still trying to use R version 3.1. I deleted it from my computer as many packages were failing to install. Then it was trying to use version 3.3, which I also had on my computer. I deleted it. The third time it was using version 3.6.3 but still had issues with "rlang" version:
![image](https://user-images.githubusercontent.com/37674030/80737311-2cec5700-8ac8-11ea-81da-efa046b61989.png)

Still, I tried to use the tutorial and got this:
![image](https://user-images.githubusercontent.com/37674030/80737361-3d043680-8ac8-11ea-80a6-7af8e36985b2.png)

Then ran AutoTest and got same error as before:
![image](https://user-images.githubusercontent.com/37674030/80737424-53aa8d80-8ac8-11ea-8f88-d0b80b3624e5.png)

**Comment by ryanpmcg** [comment]
Well, the AutoTest script will fail if the installation fails. The tutorial will also fail now because the JOSS reviewers recommended separating installation from the tutorial. The installation can fail for at least a few reasons. If you want to save time can we set up a zoom meeting so I can quickly diagnose what is happening?

**Comment by marianadobre** [comment]
Alright. Then, let's do a zoom meeting as it would save us a lot of time. Tomorrow or next week will work for me.

**Comment by ryanpmcg** [comment]
@marianadobre I set it up for 2:00 PM tomorrow since I know you are awake around that time.

Here is the link: [https://us04web.zoom.us/j/71705885433](https://us04web.zoom.us/j/71705885433)

**Comment by marianadobre** [comment]
Great! I will talk to you then.
