### ISSUE TITLE
Failed RHEL8 x64 R4.02 installation, type 'binary' is not supported on this platform

### ISSUE THREAD

**Issue by akrherz** [ryanpmcg/WEPPCLIFF#16]
I am attempting to install WEPPCLIFF on Redhat Linux 8 (64bit) using R version 4.0.2.  The error message I receive when running `sh INSTALLER/Install.sh` is:

```
Installing R package dependencies...

Error in FUN(X[[i]], ...) : 
  type 'binary' is not supported on this platform
Calls: main -> install_dependencies -> lapply -> FUN
```

I applied this diff and the installer is getting further now

```
$ git diff
diff --git a/WEPPCLIFF.R b/WEPPCLIFF.R
index b530c4a..112efb5 100644
--- a/WEPPCLIFF.R
+++ b/WEPPCLIFF.R
@@ -116,7 +116,7 @@ set_wds = function() {
 # A function to install R package dependencies on the first run.
 install_dependencies = function() {
   cat("Installing R package dependencies...", lr, lr, sep = "")
-  lapply(package.list, install.packages, lib = lib.dir, type = "binary", repos = "http://cran.us.r-project.org")
+  lapply(package.list, install.packages, lib = lib.dir, repos = "http://cran.us.r-project.org")
   cat(lr, lr, "Done.", lr, lr, sep = "")}
```

**Comment by ryanpmcg** [comment]
@akrherz That means at least one package does not have a binary install option on CRAN. Here are some potential solutions:

1. You can force the installer to compile from source by changing "binary" to "source" in any instance it shows up.
2. One reason for this may be that you are using a recent R version, and not all developers will have updated their packages to support Linux on the newest version yet. So, if the "source" option does not work, you can try the older version of R (3.6.1) which was tested on a Linux system and worked. However, I do not have the specifics of your machine, and I still can't guarantee it will work even with the older version.
3. If you are familiar with R and can install the packages necessary yourself which are listed at the bottom of the Github landing page under 'dependencies', make sure to install them in the WEPPCLIFF 'LIBRARY' directory.
4. Follow the instructions for how to make a formal 'ISSUE' on the landing page [here](https://github.com/ryanpmcg/WEPPCLIFF), and I will issue a patch to improve compatibility on Linux environments or display a message that a certain environment does not have the necessary dependency support.

I will do my best to help get it working on your Linux environment, but ultimately it may be better supported on Windows or OSX due to dependency support in those OSs.

Ryan

**Comment by akrherz** [comment]
Greetings,  Thanks for the response, I just rolled with R 3.6.3 now and things are happy it seems.  With regards to your item 4, what additional info do you need?  The page says to provide 

- [x] Your OS and applicable hardware limitations
- [x] Your version of R
- [x] Your WEPPCLIFF command
- Your input files
- Your output (if there is any) and the correct output (if applicable)
- Your WEPPCLIFF/AUTOTEST/OUTPUT folder as a .zip file (if applicable)

**Comment by ryanpmcg** [comment]
@akrherz You did everything right so far. I was anticipating you trying 1-3, getting further along (i.e. completing installation), and still having some issue come up (as in a WEPPCLIFF command not working properly), in which you would need to provide those additional items. Sorry for any confusion, just trying to address the issue quickly. Thanks for posting it, by the way. Hope everything else works well for you.

**Comment by ryanpmcg** [comment]
@akrherz If you no longer have trouble related to this issue, will you close it? You are always welcome to open a new issue if any post-installation WEPPCLIFF-Linux issues come up.
